# Generated by Django 6.0.2 on 2026-02-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
