# Generated by Django 6.0.2 on 2026-03-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_roomcategory_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.IntegerField(default='A', max_length=50),
        ),
    ]
