# Generated by Django 6.0.2 on 2026-03-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='price_per_night',
        ),
    ]
